#!/bin/bash

if [ \($1\) -a \($2\) ]
then
	t=$1;
	if [ "$1" == "-m" ]
	then
		t=$(($2 * 60));
	fi

	sleep $t;
	ogg123 /usr/share/sounds/gnome/default/alerts/glass.ogg /usr/share/sounds/gnome/default/alerts/glass.ogg /usr/share/sounds/gnome/default/alerts/glass.ogg /usr/share/sounds/gnome/default/alerts/glass.ogg -q

fi
